---
# locale_on_debian/tasks/main.yml

- name: 'Ensure desired locale exists'
  community.general.locale_gen:
    name: "{{ desired_locale }}"
    state: 'present'
  when:
    - 'ansible_os_family == "Debian"'

- name: 'Set debconf locales_to_be_generated'
  ansible.builtin.debconf:
    name: 'locales'
    question: 'locales/locales_to_be_generated'
    value: "{{ desired_locale }} UTF-8"
    vtype: 'select'
  when:
    - 'ansible_os_family == "Debian"'

- name: 'Set default locale'
  ansible.builtin.debconf:
    name: 'locales'
    question: 'locales/default_environment_locale'
    value: "{{ default_locale }}"
    vtype: 'select'
  when:
    - 'ansible_os_family == "Debian"'
